//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeControl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SafeControl.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị.
        /// </summary>
        internal static string iChuyenHuong_ADMIN {
            get {
                return ResourceManager.GetString("iChuyenHuong_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        internal static string iChuyenHuong_NGUOIDUNG {
            get {
                return ResourceManager.GetString("iChuyenHuong_NGUOIDUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kí tự (Loại 1).
        /// </summary>
        internal static string iDanhDau_CharSpecial1 {
            get {
                return ResourceManager.GetString("iDanhDau_CharSpecial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ điển.
        /// </summary>
        internal static string iDanhDau_Dictionary {
            get {
                return ResourceManager.GetString("iDanhDau_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        internal static string iDanhDau_Number {
            get {
                return ResourceManager.GetString("iDanhDau_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 ngày.
        /// </summary>
        internal static string iDaySelect_N1 {
            get {
                return ResourceManager.GetString("iDaySelect_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 năm.
        /// </summary>
        internal static string iDaySelect_N10Y {
            get {
                return ResourceManager.GetString("iDaySelect_N10Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 tuần.
        /// </summary>
        internal static string iDaySelect_N14 {
            get {
                return ResourceManager.GetString("iDaySelect_N14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,5 năm.
        /// </summary>
        internal static string iDaySelect_N1HY {
            get {
                return ResourceManager.GetString("iDaySelect_N1HY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 năm.
        /// </summary>
        internal static string iDaySelect_N1Y {
            get {
                return ResourceManager.GetString("iDaySelect_N1Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 ngày.
        /// </summary>
        internal static string iDaySelect_N2 {
            get {
                return ResourceManager.GetString("iDaySelect_N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 năm.
        /// </summary>
        internal static string iDaySelect_N20Y {
            get {
                return ResourceManager.GetString("iDaySelect_N20Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 năm.
        /// </summary>
        internal static string iDaySelect_N2Y {
            get {
                return ResourceManager.GetString("iDaySelect_N2Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ngày.
        /// </summary>
        internal static string iDaySelect_N3 {
            get {
                return ResourceManager.GetString("iDaySelect_N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tháng.
        /// </summary>
        internal static string iDaySelect_N30 {
            get {
                return ResourceManager.GetString("iDaySelect_N30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 năm.
        /// </summary>
        internal static string iDaySelect_N30Y {
            get {
                return ResourceManager.GetString("iDaySelect_N30Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 năm.
        /// </summary>
        internal static string iDaySelect_N3Y {
            get {
                return ResourceManager.GetString("iDaySelect_N3Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,5 tháng.
        /// </summary>
        internal static string iDaySelect_N45 {
            get {
                return ResourceManager.GetString("iDaySelect_N45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 ngày.
        /// </summary>
        internal static string iDaySelect_N5 {
            get {
                return ResourceManager.GetString("iDaySelect_N5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 năm.
        /// </summary>
        internal static string iDaySelect_N50Y {
            get {
                return ResourceManager.GetString("iDaySelect_N50Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 năm.
        /// </summary>
        internal static string iDaySelect_N5Y {
            get {
                return ResourceManager.GetString("iDaySelect_N5Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 tháng.
        /// </summary>
        internal static string iDaySelect_N60 {
            get {
                return ResourceManager.GetString("iDaySelect_N60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tuần.
        /// </summary>
        internal static string iDaySelect_N7 {
            get {
                return ResourceManager.GetString("iDaySelect_N7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 tháng.
        /// </summary>
        internal static string iDaySelect_NHY {
            get {
                return ResourceManager.GetString("iDaySelect_NHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string iDaySelect_NN {
            get {
                return ResourceManager.GetString("iDaySelect_NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mẫu Email.
        /// </summary>
        internal static string if8SendAPI_Email_FileAttachDialog_Email {
            get {
                return ResourceManager.GetString("if8SendAPI_Email_FileAttachDialog_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Email Active Hợp đồng.
        /// </summary>
        internal static string if8SendAPI_Email_FileAttachDialog_Email_Active_HopDong {
            get {
                return ResourceManager.GetString("if8SendAPI_Email_FileAttachDialog_Email_Active_HopDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string if8SendAPI_Email_FileAttachDialog_None {
            get {
                return ResourceManager.GetString("if8SendAPI_Email_FileAttachDialog_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mẫu Sms.
        /// </summary>
        internal static string if8SendAPI_Email_FileAttachDialog_Sms {
            get {
                return ResourceManager.GetString("if8SendAPI_Email_FileAttachDialog_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Sms Active Hợp đồng.
        /// </summary>
        internal static string if8SendAPI_Email_FileAttachDialog_Sms_Active_HopDong {
            get {
                return ResourceManager.GetString("if8SendAPI_Email_FileAttachDialog_Sms_Active_HopDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Sms Hợp đồng đến hạn.
        /// </summary>
        internal static string if8SendAPI_Email_FileAttachDialog_Sms_DenHan {
            get {
                return ResourceManager.GetString("if8SendAPI_Email_FileAttachDialog_Sms_DenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cả 2 loại.
        /// </summary>
        internal static string iIDDocumentType_CAHAILOAI {
            get {
                return ResourceManager.GetString("iIDDocumentType_CAHAILOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy.
        /// </summary>
        internal static string iIDDocumentType_GIAY {
            get {
                return ResourceManager.GetString("iIDDocumentType_GIAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu số.
        /// </summary>
        internal static string iIDDocumentType_TAILIEUSO {
            get {
                return ResourceManager.GetString("iIDDocumentType_TAILIEUSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-English.
        /// </summary>
        internal static string iLanguage_EN {
            get {
                return ResourceManager.GetString("iLanguage_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-French.
        /// </summary>
        internal static string iLanguage_FR {
            get {
                return ResourceManager.GetString("iLanguage_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-Russia.
        /// </summary>
        internal static string iLanguage_RU {
            get {
                return ResourceManager.GetString("iLanguage_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th-Thái.
        /// </summary>
        internal static string iLanguage_TH {
            get {
                return ResourceManager.GetString("iLanguage_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi-Việt Nam.
        /// </summary>
        internal static string iLanguage_VI {
            get {
                return ResourceManager.GetString("iLanguage_VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Map Satellite.
        /// </summary>
        internal static string iMapType_BingMapSatellite {
            get {
                return ResourceManager.GetString("iMapType_BingMapSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map.
        /// </summary>
        internal static string iMapType_GoogleMap {
            get {
                return ResourceManager.GetString("iMapType_GoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map Maker.
        /// </summary>
        internal static string iMapType_GoogleMapMaker {
            get {
                return ResourceManager.GetString("iMapType_GoogleMapMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Satellite.
        /// </summary>
        internal static string iMapType_GoogleSatellite {
            get {
                return ResourceManager.GetString("iMapType_GoogleSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string iOption_f8SendAPI_Email {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data.
        /// </summary>
        internal static string iOption_f8SendAPI_LoadData {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - None -.
        /// </summary>
        internal static string iOption_f8SendAPI_None {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run cURL.
        /// </summary>
        internal static string iOption_f8SendAPI_RunCUrl {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_RunCUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Send Email.
        /// </summary>
        internal static string iOption_f8SendAPI_SendEmail {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Send Sms.
        /// </summary>
        internal static string iOption_f8SendAPI_SendSms {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Send Sms-1.
        /// </summary>
        internal static string iOption_f8SendAPI_SendSms_1 {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_SendSms_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Send Sms By Batch.
        /// </summary>
        internal static string iOption_f8SendAPI_SendSmsByBatch {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_SendSmsByBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Send Sms By Template.
        /// </summary>
        internal static string iOption_f8SendAPI_SendSmsByTemplate {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_SendSmsByTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Send Sms To Firebase.
        /// </summary>
        internal static string iOption_f8SendAPI_SendSmsToFirebase {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_SendSmsToFirebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms.
        /// </summary>
        internal static string iOption_f8SendAPI_Sms {
            get {
                return ResourceManager.GetString("iOption_f8SendAPI_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên đề.
        /// </summary>
        internal static string iPhanLoaiDeTaiKhoaHoc_CHUYENDE {
            get {
                return ResourceManager.GetString("iPhanLoaiDeTaiKhoaHoc_CHUYENDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề tài.
        /// </summary>
        internal static string iPhanLoaiDeTaiKhoaHoc_DETAI {
            get {
                return ResourceManager.GetString("iPhanLoaiDeTaiKhoaHoc_DETAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch.
        /// </summary>
        internal static string iPhanLoaiDeTaiKhoaHoc_KEHOACH {
            get {
                return ResourceManager.GetString("iPhanLoaiDeTaiKhoaHoc_KEHOACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string iPhanLoaiDeTaiKhoaHoc_KHAC {
            get {
                return ResourceManager.GetString("iPhanLoaiDeTaiKhoaHoc_KHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email API.
        /// </summary>
        internal static string iSelectEmailOrSms_SendEmail {
            get {
                return ResourceManager.GetString("iSelectEmailOrSms_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Sms API.
        /// </summary>
        internal static string iSelectEmailOrSms_SendSms {
            get {
                return ResourceManager.GetString("iSelectEmailOrSms_SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Sms-1 API.
        /// </summary>
        internal static string iSelectEmailOrSms_SendSms_1 {
            get {
                return ResourceManager.GetString("iSelectEmailOrSms_SendSms_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Sms By Batch API.
        /// </summary>
        internal static string iSelectEmailOrSms_SendSmsByBatch {
            get {
                return ResourceManager.GetString("iSelectEmailOrSms_SendSmsByBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Sms By Template API.
        /// </summary>
        internal static string iSelectEmailOrSms_SendSmsByTemplate {
            get {
                return ResourceManager.GetString("iSelectEmailOrSms_SendSmsByTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Sms To Firebase API.
        /// </summary>
        internal static string iSelectEmailOrSms_SendSmsToFirebase {
            get {
                return ResourceManager.GetString("iSelectEmailOrSms_SendSmsToFirebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string iSort_Ascending {
            get {
                return ResourceManager.GetString("iSort_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string iSort_Descending {
            get {
                return ResourceManager.GetString("iSort_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string iSort_NoSort {
            get {
                return ResourceManager.GetString("iSort_NoSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2000.
        /// </summary>
        internal static string Nam_Nam2000 {
            get {
                return ResourceManager.GetString("Nam_Nam2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2001.
        /// </summary>
        internal static string Nam_Nam2001 {
            get {
                return ResourceManager.GetString("Nam_Nam2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2002.
        /// </summary>
        internal static string Nam_Nam2002 {
            get {
                return ResourceManager.GetString("Nam_Nam2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2003.
        /// </summary>
        internal static string Nam_Nam2003 {
            get {
                return ResourceManager.GetString("Nam_Nam2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2004.
        /// </summary>
        internal static string Nam_Nam2004 {
            get {
                return ResourceManager.GetString("Nam_Nam2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2005.
        /// </summary>
        internal static string Nam_Nam2005 {
            get {
                return ResourceManager.GetString("Nam_Nam2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2006.
        /// </summary>
        internal static string Nam_Nam2006 {
            get {
                return ResourceManager.GetString("Nam_Nam2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2007.
        /// </summary>
        internal static string Nam_Nam2007 {
            get {
                return ResourceManager.GetString("Nam_Nam2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2008.
        /// </summary>
        internal static string Nam_Nam2008 {
            get {
                return ResourceManager.GetString("Nam_Nam2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2009.
        /// </summary>
        internal static string Nam_Nam2009 {
            get {
                return ResourceManager.GetString("Nam_Nam2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2010.
        /// </summary>
        internal static string Nam_Nam2010 {
            get {
                return ResourceManager.GetString("Nam_Nam2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2011.
        /// </summary>
        internal static string Nam_Nam2011 {
            get {
                return ResourceManager.GetString("Nam_Nam2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2012.
        /// </summary>
        internal static string Nam_Nam2012 {
            get {
                return ResourceManager.GetString("Nam_Nam2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2013.
        /// </summary>
        internal static string Nam_Nam2013 {
            get {
                return ResourceManager.GetString("Nam_Nam2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2014.
        /// </summary>
        internal static string Nam_Nam2014 {
            get {
                return ResourceManager.GetString("Nam_Nam2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2015.
        /// </summary>
        internal static string Nam_Nam2015 {
            get {
                return ResourceManager.GetString("Nam_Nam2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2016.
        /// </summary>
        internal static string Nam_Nam2016 {
            get {
                return ResourceManager.GetString("Nam_Nam2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2017.
        /// </summary>
        internal static string Nam_Nam2017 {
            get {
                return ResourceManager.GetString("Nam_Nam2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2018.
        /// </summary>
        internal static string Nam_Nam2018 {
            get {
                return ResourceManager.GetString("Nam_Nam2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2019.
        /// </summary>
        internal static string Nam_Nam2019 {
            get {
                return ResourceManager.GetString("Nam_Nam2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2020.
        /// </summary>
        internal static string Nam_Nam2020 {
            get {
                return ResourceManager.GetString("Nam_Nam2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2021.
        /// </summary>
        internal static string Nam_Nam2021 {
            get {
                return ResourceManager.GetString("Nam_Nam2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2022.
        /// </summary>
        internal static string Nam_Nam2022 {
            get {
                return ResourceManager.GetString("Nam_Nam2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2023.
        /// </summary>
        internal static string Nam_Nam2023 {
            get {
                return ResourceManager.GetString("Nam_Nam2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2024.
        /// </summary>
        internal static string Nam_Nam2024 {
            get {
                return ResourceManager.GetString("Nam_Nam2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2025.
        /// </summary>
        internal static string Nam_Nam2025 {
            get {
                return ResourceManager.GetString("Nam_Nam2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2026.
        /// </summary>
        internal static string Nam_Nam2026 {
            get {
                return ResourceManager.GetString("Nam_Nam2026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2027.
        /// </summary>
        internal static string Nam_Nam2027 {
            get {
                return ResourceManager.GetString("Nam_Nam2027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2028.
        /// </summary>
        internal static string Nam_Nam2028 {
            get {
                return ResourceManager.GetString("Nam_Nam2028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2029.
        /// </summary>
        internal static string Nam_Nam2029 {
            get {
                return ResourceManager.GetString("Nam_Nam2029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm 2030.
        /// </summary>
        internal static string Nam_Nam2030 {
            get {
                return ResourceManager.GetString("Nam_Nam2030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 1.
        /// </summary>
        internal static string Ngay_Ngay1 {
            get {
                return ResourceManager.GetString("Ngay_Ngay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 10.
        /// </summary>
        internal static string Ngay_Ngay10 {
            get {
                return ResourceManager.GetString("Ngay_Ngay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 11.
        /// </summary>
        internal static string Ngay_Ngay11 {
            get {
                return ResourceManager.GetString("Ngay_Ngay11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 12.
        /// </summary>
        internal static string Ngay_Ngay12 {
            get {
                return ResourceManager.GetString("Ngay_Ngay12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 13.
        /// </summary>
        internal static string Ngay_Ngay13 {
            get {
                return ResourceManager.GetString("Ngay_Ngay13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 14.
        /// </summary>
        internal static string Ngay_Ngay14 {
            get {
                return ResourceManager.GetString("Ngay_Ngay14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 15.
        /// </summary>
        internal static string Ngay_Ngay15 {
            get {
                return ResourceManager.GetString("Ngay_Ngay15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 16.
        /// </summary>
        internal static string Ngay_Ngay16 {
            get {
                return ResourceManager.GetString("Ngay_Ngay16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 17.
        /// </summary>
        internal static string Ngay_Ngay17 {
            get {
                return ResourceManager.GetString("Ngay_Ngay17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 18.
        /// </summary>
        internal static string Ngay_Ngay18 {
            get {
                return ResourceManager.GetString("Ngay_Ngay18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 19.
        /// </summary>
        internal static string Ngay_Ngay19 {
            get {
                return ResourceManager.GetString("Ngay_Ngay19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 2.
        /// </summary>
        internal static string Ngay_Ngay2 {
            get {
                return ResourceManager.GetString("Ngay_Ngay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 20.
        /// </summary>
        internal static string Ngay_Ngay20 {
            get {
                return ResourceManager.GetString("Ngay_Ngay20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 21.
        /// </summary>
        internal static string Ngay_Ngay21 {
            get {
                return ResourceManager.GetString("Ngay_Ngay21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 22.
        /// </summary>
        internal static string Ngay_Ngay22 {
            get {
                return ResourceManager.GetString("Ngay_Ngay22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 23.
        /// </summary>
        internal static string Ngay_Ngay23 {
            get {
                return ResourceManager.GetString("Ngay_Ngay23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 24.
        /// </summary>
        internal static string Ngay_Ngay24 {
            get {
                return ResourceManager.GetString("Ngay_Ngay24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 25.
        /// </summary>
        internal static string Ngay_Ngay25 {
            get {
                return ResourceManager.GetString("Ngay_Ngay25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 26.
        /// </summary>
        internal static string Ngay_Ngay26 {
            get {
                return ResourceManager.GetString("Ngay_Ngay26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 27.
        /// </summary>
        internal static string Ngay_Ngay27 {
            get {
                return ResourceManager.GetString("Ngay_Ngay27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 28.
        /// </summary>
        internal static string Ngay_Ngay28 {
            get {
                return ResourceManager.GetString("Ngay_Ngay28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 29.
        /// </summary>
        internal static string Ngay_Ngay29 {
            get {
                return ResourceManager.GetString("Ngay_Ngay29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 3.
        /// </summary>
        internal static string Ngay_Ngay3 {
            get {
                return ResourceManager.GetString("Ngay_Ngay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 30.
        /// </summary>
        internal static string Ngay_Ngay30 {
            get {
                return ResourceManager.GetString("Ngay_Ngay30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 31.
        /// </summary>
        internal static string Ngay_Ngay31 {
            get {
                return ResourceManager.GetString("Ngay_Ngay31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 4.
        /// </summary>
        internal static string Ngay_Ngay4 {
            get {
                return ResourceManager.GetString("Ngay_Ngay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 5.
        /// </summary>
        internal static string Ngay_Ngay5 {
            get {
                return ResourceManager.GetString("Ngay_Ngay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 6.
        /// </summary>
        internal static string Ngay_Ngay6 {
            get {
                return ResourceManager.GetString("Ngay_Ngay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 7.
        /// </summary>
        internal static string Ngay_Ngay7 {
            get {
                return ResourceManager.GetString("Ngay_Ngay7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 8.
        /// </summary>
        internal static string Ngay_Ngay8 {
            get {
                return ResourceManager.GetString("Ngay_Ngay8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày 9.
        /// </summary>
        internal static string Ngay_Ngay9 {
            get {
                return ResourceManager.GetString("Ngay_Ngay9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string PageSize_HAIMUOI {
            get {
                return ResourceManager.GetString("PageSize_HAIMUOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000.
        /// </summary>
        internal static string PageSize_HAINGHIN {
            get {
                return ResourceManager.GetString("PageSize_HAINGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.000.
        /// </summary>
        internal static string PageSize_HAITRAMNGHIN {
            get {
                return ResourceManager.GetString("PageSize_HAITRAMNGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000.000.
        /// </summary>
        internal static string PageSize_HAITRIEU {
            get {
                return ResourceManager.GetString("PageSize_HAITRIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000.
        /// </summary>
        internal static string PageSize_MOTNGHIN {
            get {
                return ResourceManager.GetString("PageSize_MOTNGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string PageSize_MOTTRAM {
            get {
                return ResourceManager.GetString("PageSize_MOTTRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.000.
        /// </summary>
        internal static string PageSize_MOTTRAMNGHIN {
            get {
                return ResourceManager.GetString("PageSize_MOTTRAMNGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.000.000.
        /// </summary>
        internal static string PageSize_MOTTRIEU {
            get {
                return ResourceManager.GetString("PageSize_MOTTRIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.500.000.
        /// </summary>
        internal static string PageSize_MOTTRIEUNAMTRAMNGHIN {
            get {
                return ResourceManager.GetString("PageSize_MOTTRIEUNAMTRAMNGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PageSize_MUOI {
            get {
                return ResourceManager.GetString("PageSize_MUOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string PageSize_MUOILAM {
            get {
                return ResourceManager.GetString("PageSize_MUOILAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string PageSize_NAM {
            get {
                return ResourceManager.GetString("PageSize_NAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string PageSize_NAMMUOI {
            get {
                return ResourceManager.GetString("PageSize_NAMMUOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.000.
        /// </summary>
        internal static string PageSize_NAMNGHIN {
            get {
                return ResourceManager.GetString("PageSize_NAMNGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string PageSize_NAMTRAM {
            get {
                return ResourceManager.GetString("PageSize_NAMTRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.000.
        /// </summary>
        internal static string PageSize_NAMTRAMNGHIN {
            get {
                return ResourceManager.GetString("PageSize_NAMTRAMNGHIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No limit.
        /// </summary>
        internal static string PageSize_NOLIMIT {
            get {
                return ResourceManager.GetString("PageSize_NOLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 1.
        /// </summary>
        internal static string Thang_Thang1 {
            get {
                return ResourceManager.GetString("Thang_Thang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 10.
        /// </summary>
        internal static string Thang_Thang10 {
            get {
                return ResourceManager.GetString("Thang_Thang10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 11.
        /// </summary>
        internal static string Thang_Thang11 {
            get {
                return ResourceManager.GetString("Thang_Thang11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 12.
        /// </summary>
        internal static string Thang_Thang12 {
            get {
                return ResourceManager.GetString("Thang_Thang12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 2.
        /// </summary>
        internal static string Thang_Thang2 {
            get {
                return ResourceManager.GetString("Thang_Thang2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 3.
        /// </summary>
        internal static string Thang_Thang3 {
            get {
                return ResourceManager.GetString("Thang_Thang3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 4.
        /// </summary>
        internal static string Thang_Thang4 {
            get {
                return ResourceManager.GetString("Thang_Thang4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 5.
        /// </summary>
        internal static string Thang_Thang5 {
            get {
                return ResourceManager.GetString("Thang_Thang5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 6.
        /// </summary>
        internal static string Thang_Thang6 {
            get {
                return ResourceManager.GetString("Thang_Thang6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 7.
        /// </summary>
        internal static string Thang_Thang7 {
            get {
                return ResourceManager.GetString("Thang_Thang7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 8.
        /// </summary>
        internal static string Thang_Thang8 {
            get {
                return ResourceManager.GetString("Thang_Thang8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 9.
        /// </summary>
        internal static string Thang_Thang9 {
            get {
                return ResourceManager.GetString("Thang_Thang9", resourceCulture);
            }
        }
    }
}
